baseURL: "https://swasher.github.io/"
languageCode: ru-RU
title: Antiskleroz

paginate: 15
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

taxonomies:
#  author: "authors"
  tag: "tags"
  category: "categories"

disqusShortname: swasher

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Antiskleroz
  description: "Swasher's Antiskleroz"
  keywords: [Blog, Portfolio, PaperMod]
  author: Swasher
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 Января, 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: true
  showtoc: true
  tocopen: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "images/favicon-16x16.png"
    favicon16x16: "images/favicon-16x16.png"
    favicon32x32: "images/favicon-32x32.png"
    apple_touch_icon: "images/apple-touch-icon.png"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Antiskleroz"
    icon: "/images/Long-beard.png"
    iconHeight: 35

#  # profile-mode
#  profileMode:
#    enabled: false # needs to be explicitly set
#    title: ExampleSite
#    subtitle: "This is subtitle"
#    imageUrl: "<img location>"
#    imageWidth: 120
#    imageHeight: 120
#    imageTitle: my image
#    buttons:
#      - name: Posts
#        url: posts
#      - name: Tags
#        url: tags

#  # home-info mode
#  homeInfoParams:
#    Title: "Hi there \U0001F44B"
#    Content: Welcome to my blog

  socialIcons:
    - name: stackoverflow
      url: "https://stackoverflow.com/users/1334825/swasher"
    - name: github
      url: "https://github.com/swasher"
#    - name: twitter
#      url: "https://twitter.com/"


  analytics:
    google:
      SiteVerificationTag: "G-2L94Y929J6"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/swasher/swasher.github.io/blob/master/content"
    Text: "Edit" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: search
      name: search
      url: /search/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai

markup:
  highlight:
     # anchorLineNos: true
     codeFences: true
     guessSyntax: true
     lineNos: false
     style: monokai
     pygmentsCodefences: true
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: false
      xhtml: false
